name: Bug report
description: Report something broken on the site
title: "[Bug] "
labels: [bug]
assignees: []

body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Clearly describe the problem.
      placeholder: Tell me what broke…
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How do I make this happen again?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened instead?

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain.

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which OS are you using?
      options:
        - Windows 11
        - Windows 10
        - Windows 8.1 or older
        - macOS
        - Linux
        - Android
        - iOS
        - Other
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Firefox
        - Chrome
        - Edge
        - Safari
        - Opera
        - Other
    validations:
      required: true


  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Anything else we should know?
